### ISSUE TITLE
Disable annotations while selection bar is activated

### ISSUE THREAD

**Issue by ytid** [adrewind/extension#4]
Faled if YouTube ad was shown

  Scenario: Disable annotations while selection bar is activated
  ✔ Given Local storage state is "{'###guide': 3}"
  ✔ Given I am watch "2vMH8lITTCE" video
  ✔ And I skip In-Stream ad if it needed
  ✔ When I enable annotations
  ✔ And I click AD button
  ✔ And I wait "1" seconds
  ✖ Then Annotations must be disabled
  - When I click AD button
  - Then Annotations must be enabled

**Comment by xakdog** [comment]
Fixed https://github.com/adrewind/extension/commit/69508daa0d57b8c4ec0ea93bd3513ef132c55f2a
